### ISSUE TITLE
github相关问题提交（2015-12-19）

### ISSUE THREAD

**Issue by zhu869886509** [yangqiang5156/digital#2]
<table>
<tr><td>问题</td><td>解决方案</td></tr>
<tr><td>问题1：在github中上传文件的过程中出现冲突无法进行上传</td><td>将web端的文件先克隆到本地，再向github中进行上传文件</td></tr>
<tr><td>问题2：上传过程中报错everything up-to-data</td><td>将项目删除并重新clone到本地</td></tr>
<tr><td>问题3：上传过程中报错Your branch is up-to-date with 'origin/master'.</td><td>将项目删除并重新clone到本地</td></tr>

</table>

**Comment by yangqiang5156** [comment]
什么玩意儿

**Comment by jiyangli** [comment]
删除项目，重新clone到本地

**Comment by yangqiang5156** [comment]
> 删除项目，重新clone到本地

重新弄了，代码可以提交了。
