### ISSUE TITLE
排版布局+特效想过问题提交（2016.1.3）

### ISSUE THREAD

**Issue by zhu869886509** [yangqiang5156/digital#3]
<table>
<tr><td>问题</td><td>解决方案</td></tr>
<tr><td>问题一：瀑布流图片在加载的过程中部分图片不显示</td><td>原因是因为随机选取的数不是从0开始，将数值改成零开始就可以</td></tr>
<tr><td>问题二：排版布局的过程中盒子有高却背景颜色没有显示。</td><td>原因是盒子内部元素有浮动所以高没有被解析出来，在盒子本身加overf：hidden或清除浮动</td></tr>
<tr><td>问题三：电商当中价格表的降序排列用sort如何实现</td><td>未解决</td></tr>
<tr><td>问题三：ajax获取数据过程中，将文件夹data放在与public同一目录下路径用../data/11.html和/data/11.html获取不到数据，但是放在public中就可以获取到数据。</td><td>具体原因不明确</td></tr>
</table>

**Comment by jiyangli** [comment]
数字排序方法：
function sortNum(a, b){return a - b};  //a-b升序 b-a 降序
//arr.sort()  ASCII排序
arr.sort(sortNum)  // 数值排序
